		<h2>Home</h2>
		<p>&Uuml;berall dieselbe alte Leier. Das Layout ist fertig, der Text l&auml;sst auf sich warten. Damit das Layout nun nicht nackt im Raume steht und sich klein und leer vorkommt, springe ich ein: der Blindtext. Genau zu diesem Zwecke erschaffen, immer im Schatten meines gro&szlig;en Bruders &raquo;Lorem Ipsum&laquo;, freue ich mich jedes Mal, wenn Sie ein paar Zeilen lesen.</p>
		<h3>Blindtext H3</h3>
		<p> Denn esse est percipi - Sein ist wahrgenommen werden. Und weil Sie nun schon die G&uuml;te haben, mich ein paar weitere S&auml;tze lang zu begleiten, m&ouml;chte ich diese Gelegenheit nutzen, Ihnen nicht nur als L&uuml;ckenf&uuml;ller zu dienen, sondern auf etwas hinzuweisen, das es ebenso verdient wahrgenommen zu werden: Webstandards n&auml;mlich.</p>
		<h4>Blindtext H4</h4>
		<p> Sehen Sie, Webstandards sind das Regelwerk, auf dem Webseiten aufbauen. So gibt es Regeln f&uuml;r HTML, CSS, JavaScript oder auch XML; Worte, die Sie vielleicht schon einmal von Ihrem Entwickler geh&ouml;rt haben. Diese Standards sorgen daf&uuml;r, dass alle Beteiligten aus einer Webseite den gr&ouml;&szlig;ten Nutzen ziehen.</p>

		<p> Im Gegensatz zu fr&uuml;heren Webseiten m&uuml;ssen wir zum Beispiel nicht mehr zwei verschiedene Webseiten f&uuml;r den Internet Explorer und einen anderen Browser programmieren. Es reicht eine Seite, die - richtig angelegt - sowohl auf verschiedenen Browsern im Netz funktioniert, aber ebenso gut f&uuml;r den Ausdruck oder die Darstellung auf einem Handy geeignet ist. Wohlgemerkt: Eine Seite f&uuml;r alle Formate.</p>
		<h4>Blindtext H4</h4>
		<p> Was f&uuml;r eine Erleichterung. Standards sparen Zeit bei den Entwicklungskosten und sorgen daf&uuml;r, dass sich Webseiten sp&auml;ter leichter pflegen lassen. Nat&uuml;rlich nur dann, wenn sich alle an diese Standards halten. Das gilt f&uuml;r Browser wie Firefox, Opera, Safari und den Internet Explorer ebenso wie f&uuml;r die Darstellung in Handys. Und was k&ouml;nnen Sie f&uuml;r Standards tun? Fordern Sie von Ihren Designern und Programmieren einfach standardkonforme Webseiten. Ihr Budget wird es Ihnen auf Dauer danken. Ebenso m&ouml;chte ich Ihnen daf&uuml;r danken, dass Sie mich bin zum Ende gelesen </p>